// Front-end/electronic-signature-frontend/src/stories/Button.tsx
import './button.css';

interface ButtonProps {
  /**
   * Is this the principal call to action on the page?
   */
  primary?: boolean;
  /**
   * What background color to use
   */
  backgroundColor?: string;
  /**
   * How large should the button be?
   */
  size?: 'small' | 'medium' | 'large';
  /**
   * Button contents
   */
  label: string;
  /**
   * Optional click handler
   */
  onClick?: () => void;
}

/**
 * Primary UI component for user interaction
 */
export const Button = ({
  primary = false,
  size = 'medium',
  backgroundColor,
  label,
  ...props
}: ButtonProps) => {
  const mode = primary
    ? 'storybook-button--primary'
    : 'storybook-button--secondary';
  return (
    <button
      type="button"
      className={['storybook-button', `storybook-button--${size}`, mode].join(
        ' ',
      )}
      style={{backgroundColor}}
      {...props}>
      {label}
    </button>
  );
};

// Front-end/CXM-Front/libs/shared/ui/button/src/lib/button/button.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';

@Component({
  selector: 'cxm-smartflow-button',
  templateUrl: './button.component.html',
  styleUrls: ['./button.component.scss'],
})
export class ButtonComponent {
  /**
   * Is this the principal call to action on the page?
   */
  @Input()
  primary = false;

  @Input()
  labelColor?: string;

  /**
   * What background color to use
   */
  @Input()
  backgroundColor?: string;

  @Input()
  borderRadius?: string;

  /**
   * How large should the button be?
   */
  @Input()
  size: 'small' | 'medium' | 'large' = 'medium';

  /**
   * Button contents
   *
   * @required
   */
  @Input()
  label = 'Button';

  @Input()
  width: string;

  @Input()
  margin: string;

  @Input()
  fontSize: string;

  @Input()
  fontWeight: string;

  @Input()
  disable = false;

  @Input()
  pathRouterLink: string;

  @Input()
  cxmClass = ['']
  @Input()
  cxmStyle: any;

  // eslint-disable-next-line @angular-eslint/no-output-on-prefix
  @Output()
  onClick = new EventEmitter<Event>();

  public get classes(): string[] {
    const mode = this.primary
      ? 'storybook-button--primary'
      : 'cxm-btn cxm-btn-primary';
    return ['storybook-button', `storybook-button--${this.size}`, mode,].concat(this.cxmClass);
  }
}

<button
  (click)="onClick.emit($event)"
  [ngClass]="classes"
  [ngStyle]="{
    'background-color': backgroundColor,
    'border-radius': borderRadius,
    'color': labelColor,
    'width': width,
    'font-weight': fontWeight,
    'font-size': fontSize
  }"
  [disabled]="disable"
>
  {{ label }}
</button>
